name: Notify Monorepo

on:
  push:
    branches: [ 'main' ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          repository: CommandLineFox/VetAppMono
          event-type: update-submodule
          client-payload: '{"repo": "${{ github.event.repository.name }}", "sha": "${{ github.sha }}"}'